---

# First playbook start

- name: Install and Start nginx
  hosts: all
  become: true

  tasks:
   - name: Install nginx
     apt:
      name: nginx
      state: present

   - name: Started nginx
     service:
      name: nginx
      state: started

# First playbook end